# whenever we push to main, master or release branch.
trigger:
  tags:
    include:
      - v*.*.*

variables:
    - group: release-variables_plugin
    - name: taggedVersion
      value: ${{ replace(variables['Build.SourceBranchName'], 'v') }}
  

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Npm@1
    displayName: 'Set version in Package.json to $(taggedVersion)'
    inputs:
      command: custom
      verbose: true
      customCommand: '--no-git-tag-version version $(taggedVersion)'
  - task: Npm@1
    displayName: 'Publish package to internal feed'
    inputs:
      command: publish
      verbose: true
      publishRegistry: useFeed
      publishFeed: $(publishFeed)
  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourceBranchName)'
    inputs:
      rootFolderOrFile: "$(Pipeline.Workspace)/s"
      archiveFile: '$(Build.SourceBranchName)_$(Build.BuildId).zip'
  - task: PublishPipelineArtifact@1
    displayName: "Add published output to pipeline artifacts"
    inputs:
      targetPath: "$(Pipeline.Workspace)/s"
      artifactName: "$(Build.SourceBranchName)"
