# whenever we push to main, master or release branch.

trigger:
  tags:
    include:
      - v*.*.*

variables:
    - group: release-variables_plugin
    - name: taggedVersion
      value: ${{ replace(variables['Build.SourceBranchName'], 'v') }}

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm ci
    displayName: "Install dependencies"

  - script: |
      npm run build
    displayName: "Build project"

  - task: Npm@1
    displayName: 'Set version in Package.json to $(taggedVersion)'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: '--no-git-tag-version version $(taggedVersion)'

  - task: PublishPipelineArtifact@1
    displayName: "Add published output to pipeline artifacts"
    inputs:
      targetPath: "$(Build.SourcesDirectory)"
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**/dist/*'
      TargetFolder: '$(System.DefaultWorkingDirectory)'
  - task: Npm@1
    displayName: 'Publish package to internal feed'
    inputs:
      command: 'publish'
      verbose: true
      publishRegistry: 'useFeed'
      publishFeed: '$(publishFeed)'

