# whenever we push to main, master or release branch.
trigger:
  tags:
    include:
      - v*.*.*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: PublishPipelineArtifact@1
    displayName: "Add publish output to pipeline artifacts"
    inputs:
      targetPath: "$(Pipeline.Workspace)"
      artifactName: "$(Build.SourceBranchName)"
