# whenever we push to main, master or release branch.
trigger:
  tags:
    include:
      - v*.*.*

variables:
  - group: release-variables_plugin
  - name: taggedVersion
    value: ${{ replace(variables['Build.SourceBranchName'], 'v') }}

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: ArchiveFiles@2
    displayName: "Archive $(Build.SourceBranchName)"
    inputs:
      rootFolderOrFile: "$(Pipeline.Workspace)/s"
      archiveFile: "$(Build.SourceBranchName)_$(Build.BuildId).zip"
  - task: UniversalPackages@0
    displayName: "Publish package to feed"
    inputs:
      command: publish
      vstsFeedPublish: $(vstsFeedPublish)
      vstsFeedPackagePublish: $(vstsFeedPackagePublish)
      versionOption: custom
      versionPublish: $(taggedVersion)
  - task: PublishPipelineArtifact@1
    displayName: "Add publish output to pipeline artifacts"
    inputs:
      targetPath: "$(Pipeline.Workspace)/s"
      artifactName: "$(Build.SourceBranchName)"
