# whenever we push to main, master or release branch.

trigger:
  tags:
    include:
      - v*.*.*

variables:
    - group: release-variables_plugin
    - name: taggedVersion
      value: ${{ replace(variables['Build.SourceBranchName'], 'v') }}

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Npm@1
    displayName: 'Set version in Package.json to $(taggedVersion)'
    inputs:
      command: 'custom'
      customCommand: '--no-git-tag-version version $(taggedVersion)'
  - task: DeleteFiles@1
    inputs:
      Contents: |
        !(dist)
        !(manifest.json)
        !(package.json)
        !(README.md)
      RemoveDotFiles: true
  - task: Npm@1
    displayName: 'Publish package to internal feed'
    inputs:
      command: 'publish'
      verbose: true
      publishRegistry: 'useFeed'
      publishFeed: '$(publishFeed)'

