# Run CI on each PR.
# Doesn't work in Azure DevOps (yet), but showing intent.
pr:
  branches:
    include:
    - 'feature*'

# whenever we push to main, master or release branch.
trigger:
  branches:
    include:
    - main
    - releases/*
    - prereleases/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm ci
    displayName: "Install dependencies"

  - script: |
      npm run build
    displayName: "Build project"

  - script: |
      npm run lint
    displayName: "ESlint test"

  - task: Npm@1
    displayName: Jest Testing
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: run test
