# Run CI on each PR.
# Doesn't work in Azure DevOps (yet), but showing intent.
pr:
  branches:
    include:
      - "feature*"

# whenever we push to main, master or release branch.
trigger:
  branches:
    include:
      - main
      - releases/*
      - prereleases/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm ci
    displayName: "Install dependencies"

  - script: |
      npm run build
    displayName: "Build project"

  - script: |
      npm run lint
    displayName: "ESlint test"

  - script: |
      npm run test:api
    displayName: "Jest test API client"
    env:
      BASE_URL: $(BASE_URL)
      CLIENT_KEY: $(CLIENT_KEY)
      SOURCE_KEY: $(SOURCE_KEY)
  
  - script: |
      npm run test:eventHub
    displayName: "Jest test eventHub"

